version: '3.4'

services:
  todolist-backend:
    image: todolistbackend
    build:
      context: .
      dockerfile: TodoList-Backend/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=dbpost; port=5432;User Id=postgres;Password=password;Database=Todo; 
    ports:
      - 8080:8080
    depends_on:
     - "dbpost"
    networks:
     - main-net
    restart: always




  dbpost:
    image: postgres:latest
    container_name: dbpost
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: Todo
    ports:
      - "5432:5432"
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
     - main-net

networks:
  main-net:
    driver: bridge


volumes:
  app_data:
