apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todolist-database
  name: todolist-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todolist-database
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        resources: {}
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "Todo"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
status: {}
